spring.application.name=myapp

spring.mongodb.host=localhost
spring.mongodb.port=27017
spring.mongodb.database=productdb

# Security
spring.security.user.name=admin
spring.security.user.password=admin123
